name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject API token into vercel config
        uses: sergeysova/jq-action@v2
        id: rewrites
        with:
          cmd: 'jq . | .rewrites[0].has[0].value = "Bearer ${{ secrets.PUB_LYCHEE_KEY }}" | .rewrites[0].destination = "${{ secrets.LYCHEE_BASE_URL }}" vercel.json > tmpvercel.json && mv tmpvercel.json vercel.json'

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}